### ISSUE TITLE
提示不够明显

### ISSUE THREAD

**Issue by cr2121** [hustcc/PTHospital.chrome#1]
不特意看注意不到

**Comment by hustcc** [comment]
用什么形式的提醒了？背景变红？红色边框？还是alert？
求帮忙想想…

**Comment by hustcc** [comment]
在网站顶部加一栏红色背景的提示文字，高度大概50px…
这样比较好…

**Comment by hustcc** [comment]
![image](https://cloud.githubusercontent.com/assets/7856674/15018505/5e5f5dee-124c-11e6-8e3a-1d1b7ca5b03c.png)

这样提示可好？

**Comment by lolstudio** [comment]
右上角提示不明显，建议直接给个dialog提示框，因为父母不会装插件，一般是儿女帮父母装的，建议内容为”xx为莆田系医院，莆田是xx的，请谨慎就医，请联系自己的儿女“。

**Comment by hustcc** [comment]
![image](https://cloud.githubusercontent.com/assets/7856674/15035298/01d44b68-12b3-11e6-9281-af98667e6718.png)

直接在网站下方接入一条红色的提示，提示医院是莆田系，就医谨慎，这样可以吗？

**Comment by lolstudio** [comment]
我觉得还是给个提示框比较好，下方的红色提示还是不够突出且每个网站样式不一，有些网站遮挡住了，给弹窗好些，且没有兼容的问题，希望采纳。

**Comment by hustcc** [comment]
如果使用alert其实不够，因为很多垃圾网站就是很多弹窗，加上现在的网络运营商各种劫持也喜欢alert，需要一个好一点的提示方式。^-^~

**Comment by ycrao** [comment]
可以考虑透明层满屏遮盖5s，后续解除

**Comment by lolstudio** [comment]
既然”他们“劫持的话，干脆直接在打开莆田系网站时，让整个页面变红加tip再加一个确认按钮，确认才能进去网站。

**Comment by hustcc** [comment]
@ycrao @lolstudio 这个想过使用chrome提示危险的那个页面~~~我觉得可以~

**Comment by ZJsnowman** [comment]
再说大家直接把这些网站黑了得了.估计已经有人在做了

**Comment by hustcc** [comment]
@ZJsnowman 这也不靠谱，有些病该看还是得看，莆田系势力那么大~

**Comment by ghost** [comment]
怎么没有提醒呢？

http://www.xngxw.com/
http://www.whyestar.com/

**Comment by hustcc** [comment]
@kangland 今天还没有和源项目更新医院数据，晚上更新上新版本~^-^

**Comment by ghost** [comment]
我觉得除了做个莆田系医院提醒，也把非莆田系的医院也罗列一下啊。

**Comment by hustcc** [comment]
@kangland 嗯，是的，可以提醒就医注意。但是主要是数据比较难收集~

能够将莆田系收集全面就非常非常不错了~

**Comment by ghost** [comment]
一是数据比较难以收集，二是。如何确定数据的准确性。三是。如何确定数据的真实性

开启迭代模式吧。

**Comment by hustcc** [comment]
嗯。目前是直接从源项目同步数据，如果有愿意贡献数据的，我也把那个文件单独出来，直接按照样子填充医院信息即可。

**Comment by ghost** [comment]
我也不懂，无法确定数据准确性和真实性。、
希望这么好的插件，别又来一个 百度竞价了。

通常 科技公司的不懂得跨界行业的东西，其他行业的把科技产品当做利益工具而已。

**Comment by ztmdsbt** [comment]
提示不够明显. 起码把页面盖住50%.

**Comment by kevinandleekai** [comment]
不打击也不支持，我觉得单单靠这种方式并不能解决根本性的问题，万一被有心人利用了也说不定

**Comment by ghost** [comment]
要是有 哪些医院是欺诈型 ？ 哪些医生是庸医？ 的 list 那就更好了。哈哈哈哈哈哈哈哈

**Comment by lolstudio** [comment]
昨天刚发现，猎豹浏览器刚加入了一个这样的功能，lz可以搜索参考下，链接找不到了。。

**Comment by hustcc** [comment]
@lolstudio 是的，我知道猎豹安全助手，还没有使用，不知道他的效果是怎么样的~
