### ISSUE TITLE
莆田系医院名单

### ISSUE THREAD

**Issue by llyuan1993** [hustcc/PTHospital.chrome#10]
http://www.dzwww.com/xinwen/shehuixinwen/201605/t20160503_14233876.htm
我觉得应该能包含绝大部分了 推荐使用

**Comment by hustcc** [comment]
已经有比这个更全面的数据，并且包含网址~

**Comment by llyuan1993** [comment]
然而我上其中的阳光女子啥的网站 没有提示莆田系哦

**Comment by hustcc** [comment]
@llyuan1993 因为找不到他的官网。。。囧~
可以帮忙收集一下，然后到 #7 中提交信息，就可以在插件中生效了。
