### ISSUE TITLE
360之类的伪浏览器能兼容么？

### ISSUE THREAD

**Issue by yanhuixie** [hustcc/PTHospital.chrome#12]
用chrome的大概主要还是IT人，，干这行的本来就不太容易受骗。。
真正容易受骗的人，十之八九都在用着360之类或不请自来的伪浏览器。。
按理说都是chromium、webkit内核，应该可以兼容吧？

**Comment by hustcc** [comment]
是的，理论可以兼容。没有测试，不排除被厂商修改一部分，如果可以，麻烦帮忙测试下…
