### ISSUE TITLE
关于法律风险

### ISSUE THREAD

**Issue by yanhuixie** [hustcc/PTHospital.chrome#13]
最好咨询一下熟悉的律师或其他法律顾问，注意规避法律风险。
用意虽好，但标靶不一定是善类，如果和小人过招不能只有满腔热血。
特此提示。

**Comment by hustcc** [comment]
非常感谢提醒，你从事相关行业不？我对这些不太了解…

**Comment by yanhuixie** [comment]
如果你的标靶持有合法的（不管怎么合法的）工信部和公安部备案（看首页底部），那么它就是一家合法运营的网站，屏蔽它就会涉嫌违法，它可以起诉你侵犯合法权益。我是个码农，并非专业人士，仅供您参考。
