### ISSUE TITLE
增加医院名单

### ISSUE THREAD

**Issue by ghost** [hustcc/PTHospital.chrome#21]
### 证据
- 原链接已删除:
  http://www.baidu.com/link?url=sM2GCKfZ0rsMwner2PewVWs6fOW8PaHaJ7F_QAO4FBOwn-g_eTbrYvZQSrnUr_b_5sIaMbl7Q-UQSWiIQyTF1_&wd=&eqid=f042a6f100009c5700000002572c39c5
  <br/>百度快照:
  http://cache.baiducontent.com/c?m=9f65cb4a8c8507ed4fece763105e8d3b4501cb382bd7a74e2b83cf1d84642c101a39fee7706751198b8e34261caf4b5fe9f52b79300827b58cc8ff0b87fdcd763bcd7a742613913065c46ea9dc3652d653e44de8df0e97bde744e0b9d3a3c82559dd27736d80819c2a0a03bb64e71541f4d7ed5f655507caef27118f&p=866e8f0685cc43ff57e9930c540c&newp=9e778e15d9c746fe4ebe9b7c4b0792695803ed6036d7d04469&user=baidu&fm=sc&query=%CE%E4%BE%AF%B5%DA%C8%FD+%B8%C9%CF%B8%B0%FB&qid=f042a6f100009c57&p1=2
- 用户反馈:
- http://www.baidu.com/link?url=wsfbpv5ZpFxfbjPwOcVo99zniNbSiTPi8g2unY6vsNzv3CBDkB_2Qelhmr_hDxsG&wd=&eqid=f042a6f100009c5700000002572c39c5
- http://tieba.baidu.com/p/1314782031
- http://www.baidu.com/link?url=QTIMEmb67G2coYZvKz3yhP8d8dLRvfDJ491AkdyzyPek6bgqJCGWQYym3MI0EKFJU-0pJlZDtjhl7l9XNmjrba&wd=&eqid=f042a6f100009c5700000002572c39c5
  <br/>百度快照:http://cache.baiducontent.com/c?m=9d78d513d9d430d84f9a92697d61c0156d4381132ba7d70209a78449e3732a4b501295ac27530774d9d20d6c16ae394b9b8421023d1450b58cbcf85e9afbcc2775ce6176671df55c0f965ceadc46528b7bd310a3b81990e6a7748efe858f8e070f9c18127af7b2d1181715be3bab4226e2d09a4b025f14e1bb2764895a722c9d23&p=8b2a975bc0890ae909bd9b7c5a&newp=c3769a47c8934ead01a5823d1c53d8234f08d30e3ec9&user=baidu&fm=sc&query=%CE%E4%BE%AF%B5%DA%C8%FD+%B8%C9%CF%B8%B0%FB&qid=f042a6f100009c57&p1=8

**Comment by hustcc** [comment]
可以提供他的网址和电话吗？
