### ISSUE TITLE
插件存在问题

### ISSUE THREAD

**Issue by XuJincai** [hustcc/PTHospital.chrome#24]
你好，安装了这个插件，测试了下，有两个问题。
1、上海远大心胸医院，百度和google搜索出来显示的结果不一样，google没有提示是莆田系
![image](https://cloud.githubusercontent.com/assets/16322049/15202880/cc2d9aa4-1830-11e6-80a9-ff3572c4c850.png)
![image](https://cloud.githubusercontent.com/assets/16322049/15202885/e02496d4-1830-11e6-8461-4cde125309bb.png)
2、上饶协和医院，百度和google搜索都未显示是莆田系
![image](https://cloud.githubusercontent.com/assets/16322049/15202897/f4860dd8-1830-11e6-8b90-a4f35c8b0deb.png)
![image](https://cloud.githubusercontent.com/assets/16322049/15202905/fc849f68-1830-11e6-9fff-b4d763a43d30.png)

**Comment by hustcc** [comment]
感谢反馈~
1. 谷歌还没有加上医院提示，v1.1.2加了百度的。
2. 上饶协和医院，可能是因为数据中没有录入该医院。

**Comment by hustcc** [comment]
![image](https://cloud.githubusercontent.com/assets/7856674/15202982/e2ee3cb6-1831-11e6-8c1f-7bcff8fac8e3.png)
我这里是提示更新的，建议你更新插件版本，并且重启浏览器更新最新数据~

**Comment by hustcc** [comment]
上海远大心胸医院 无效，是因为这个网站对插件进行屏蔽，已经在1.1.3版本中反屏蔽。

**Comment by hustcc** [comment]
fixed 9c96b76cadfb74d7f939e75e0d11319d7c34e840
