### ISSUE TITLE
反屏蔽漏洞

### ISSUE THREAD

**Issue by facetothefate** [hustcc/PTHospital.chrome#26]
以下均在http://www.yodak.net/templets/js/fkGoogle.js 
下用控制台测试。

**没有对mask的内容进行校验：**
修改子节点

``` js
var mask = document.getElementById("89HYUX3I2Q3O6A6")
mask.innerHTML = "";

```

结果：
![image](https://cloud.githubusercontent.com/assets/4744394/15257413/3558d7b2-1914-11e6-8a0f-d456a97354b9.png)

可以再插入一张完全白色的image，改成100% 100%
这样就完全看不到了。

**没有检查父节点：**

把mask装到一个不在dom上的节点里

``` js
var container = document.createElement('div')
container.appendChild(mask);
```

结果：

如图，dom里不再有mask：
![image](https://cloud.githubusercontent.com/assets/4744394/15257820/47512ddc-1916-11e6-8b84-cd75abb05287.png)

mask被屏蔽

**因为位置固定：**
插入一张空白image 悬在mask的上面。找到mask，同级在后面插入一个相同大小z-index元素 盖上

添加一个如图的元素即可：
![image](https://cloud.githubusercontent.com/assets/4744394/15258126/cc2529f4-1917-11e6-9a1d-7795b5dcec75.png)

**Comment by facetothefate** [comment]
校验内容是否被修改，如果被修改就改回来。
校验头节点是否是原始插入节点，不是就append回去
位置的话，检查自己是不是父节点的最后一个子节点。

**Comment by hustcc** [comment]
非常感谢提醒，如果方便的话，希望能够共同开发维护，360版本已经提审~
