### ISSUE TITLE
阿波罗男子医院不是莆田的？不支持 Google 有什么意义？

### ISSUE THREAD

**Issue by LuvLetter** [hustcc/PTHospital.chrome#27]
![image](https://cloud.githubusercontent.com/assets/9290109/15453250/55f439f0-1fd4-11e6-868d-2192768e9216.png

**Comment by LuvLetter** [comment]
发现问题了，类似域名太多用于推广，而主域名往往在后面
应该增加拼音匹配和关键词匹配

**Comment by hustcc** [comment]
图片中不是已经提示是莆田医院了吗？
