### ISSUE TITLE
插件已经失效惹

### ISSUE THREAD

**Issue by MeowSalty** [hustcc/PTHospital.chrome#32]
插件似乎已经被屏蔽或者无法正常运行了
![snipaste_2018-06-07 19_19_25](https://user-images.githubusercontent.com/7829265/41096647-d6093a5a-6a87-11e8-817a-1bd87f9ac002.png)
![snipaste_2018-06-07 19_19_38](https://user-images.githubusercontent.com/7829265/41096644-d59344da-6a87-11e8-9c91-f8d09340db23.png)
![snipaste_2018-06-07 19_20_02](https://user-images.githubusercontent.com/7829265/41096643-d51e5d1e-6a87-11e8-9176-21d26d37f1d1.png)

**Comment by einsitang** [comment]
已提交PR，需要的话可以访问（AD）：https://github.com/forfuns/PTHospital.chrome
