### ISSUE TITLE
部分在readme中的医院未弹提醒

### ISSUE THREAD

**Issue by jason19659** [hustcc/PTHospital.chrome#6]
比如 http://www.qdszyy.com/
部分医院跳转到其他域名，比如 
 http://www.whablnk.com/  -> http://www.ablnanke.com/

**Comment by hustcc** [comment]
感谢反馈。
包括刚刚另外一个朋友反馈下面两个网址也不行。
http://www.xngxw.com/
http://www.whyestar.com/

今天还没有和源项目同步医院数据，晚上我来同步之后发布最新版本插件。也希望可以到[issues/7](https://github.com/hustcc/PTHospital.chrome/issues/7)这里`补充医院信息`，感谢。

**Comment by jason19659** [comment]
等新版本发布之后吧，再找一找没cover到的。

**Comment by hustcc** [comment]
好的，感谢，也可以直接pr进来~~~

**Comment by hustcc** [comment]
@jason19659 新版本已经发布，1.0.5版本，并加在该项目中加入webhook，pr merge之后自动将项目的数据推送到cdn，然后插件自动生效，不用每次更新版本，欢迎pr医院数据。
