### ISSUE TITLE
莆田系医院信息补充

### ISSUE THREAD

**Issue by hustcc** [hustcc/PTHospital.chrome#7]
方便不想PR的同学来提交医院信息，格式如下：

``` js
“医院网址”: ["医院名称", "医院电话", "其他信息，没有可以为空"],
```

注意`医院网址`无须带`http://`

只有完全的数据，才能起插件到良好的警示作用。

**Comment by ztmdsbt** [comment]
最好用统一来源的数据.
自己维护一份很难保证真实有效.

**Comment by hustcc** [comment]
@ztmdsbt 项目中有一个py脚本是从[另外那个项目](https://github.com/open-power-workgroup/Hospital)中同步数据过来的。
